#name
name: "4 - Deploy Prod"

#event
on:
  pull_request:
    types:
      - closed
    branches:
      - main

#jobs
jobs:  
  deploy-prod:
    runs-on: ubuntu-latest    
    steps:
      - name: Deploy Prod
        run: echo "Deploy em produção"